apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: aymenkani/app.streamapp
---
apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec: 
  selector:
    app: app
  ports:
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000